name: Build Release

on:
 create:
  tags:
  - v*.*.*
 pull_request:
   branches:
   - master
 push:
  branches:
  - master
 workflow_dispatch:
  
   

jobs: 
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x86, x64]    
    steps:
    - uses: actions/checkout@v2
       
    - name: build
      working-directory: ${{ env.GITHUB_WORKSPACE }} 
      shell: cmd
      run: |
         call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.platform }}
         mkdir %GITHUB_WORKSPACE%/build
         cmake -S %GITHUB_WORKSPACE% -B "%GITHUB_WORKSPACE%/build" -G Ninja -DCMAKE_BUILD_TYPE:STRING="Release"
         cmake --build "%GITHUB_WORKSPACE%/build

    - name: pack file
      run: |
       Compress-Archive -Path ./build/Scoop-Search/Scoop-Search.exe -DestinationPath ./${{ matrix.platform }}-Release.zip
       
    - name: release
      uses: softprops/action-gh-release@v2
      if: github.event.ref_type == 'tag'
      with:
        files: ./${{ matrix.platform }}-Release.zip
        prerelease: false
        make_latest: true
